Fix Ctrl-C not abandoning a pomodoro sometimes
It's possible for Ctrl-C to not have the intended effect of abandoning
the current pomodoro.  This is subject to pretty specific timing and
chance: the interrupt has to be received just as the time is changed.
The bug is caused by any function that was invoked by the `pomodoro()`
function being executed when SIGINT is received.  The inner function
returns 1 (SIGINT trap), but the `pomodoro()` function does not return;
the `state` variable is set to 0, but the timer continues.

When Ctrl-C is pressed again after this happened, the program terminates
rather than only abandoning the current pomodoro and prompting the user
to restart it.

This commit hopefully fixes all of that.

diff --git a/muccadoro b/muccadoro
--- a/muccadoro
+++ b/muccadoro
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-set -o nounset
+set -o nounset -o pipefail
 
 declare -i silly=1
 
@@ -135,7 +135,9 @@ on-tstp() {
 trap on-tstp TSTP
 
 count-state() {
-   trap 'trap on-int INT; on-int; return 1' INT
+   # 130 is the exit status for termination by Ctrl-C.  See
+   # <http://www.tldp.org/LDP/abs/html/exitcodes.html>.
+   trap 'trap on-int INT; on-int; return 130' INT
    state=1
 }
 
@@ -162,17 +164,41 @@ on-int() {
    fi
 }
 
+# XXX: beware of bugs due to SIGINT (Ctrl-C) being received during the short timeframe in
+# which another function invoked by this one is executing.  The `return 1` statement of
+# the SIGINT trap will be ran in the context of the innter function.
 pomodoro() {
    count-state
    while :; do
       # Handle signals immediately, not after `sleep` exits.  See
       # <http://mywiki.wooledge.org/SignalTrap#When_is_the_signal_handled.3F>.
       sleep 1 &
-      pp "$(figlet -f small "$((seconds/60)):$(printf '%02d' $((seconds%60)))" |
-            cowtell)"
+      # See <http://mywiki.wooledge.org/BashFAQ/002>.
+      the_time=$((seconds/60)):$(printf '%02d' $((seconds%60)))
+      # Keep in mind that almost everything causes new values to be assigned to `$?`:
+      #    $ false
+      #    $ (( $? )) && echo $?
+      #    0
+      #    $ false || { (( $? != 148 )) && echo $?; }
+      #    0
+      # In both cases, when `echo $?` is executed, `$?` is no longer 1.
+      fail=$?
+      if (( fail && fail != 148 )); then
+         return $fail
+      fi
+      text=$(figlet -f small "$the_time" | cowtell)
+      fail=$?
+      if (( ! fail )); then
+         pp "$text"
+         fail=$?
+         (( fail && fail != 148 )) && return $fail
+      elif (( fail != 148 )); then
+         return $fail
+      fi
       wait
-      ((--seconds <= 0)) && break
+      ((--seconds <= 0)) && return 0
    done
+   return 1
 }
 
 flush-stdin() {
@@ -189,7 +215,9 @@ pause() {
 for (( n=1; n<=num_pomodoros; ++n )); do
    declare -i seconds=$duration
    start_time=$(date +'%H:%M')
-   pomodoro || {
+   pomodoro
+   fail=$?
+   if (( fail == 130 )); then
       summary+="Abandoned: $start_time to $(date +'%H:%M')\n"
       # Pomodoros are atomic.
       pp "$(cowsay -d -W $(($(tput cols)-3)) 'You abandoned pomodoro '$n'.  Press any' \
@@ -197,7 +225,9 @@ for (( n=1; n<=num_pomodoros; ++n )); do
       pause
       (( --n ))
       continue
-   }
+   elif (( fail )); then
+      exit $fail
+   fi
    pause-state
    tty_settings=$(stty -g)
    stty susp undef
